/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Brutalist Editorial Design Tokens - Mapped to CSS variables for dynamic themes
        "primary-fixed": "var(--primary-fixed)",
        "surface-container": "var(--surface-container)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "tertiary-container": "var(--tertiary-container)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "on-surface": "rgb(var(--on-surface) / <alpha-value>)",
        "on-secondary-container": "var(--on-secondary-container)",
        "inverse-surface": "var(--inverse-surface)",
        "primary-container": "var(--primary-container)",
        "error": "var(--error)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "surface": "rgb(var(--surface) / <alpha-value>)",
        "error-dim": "var(--error-dim)",
        "on-tertiary": "var(--on-tertiary)",
        "secondary": "var(--secondary)",
        "on-error": "var(--on-error)",
        "surface-container-low": "var(--surface-container-low)",
        "secondary-container": "var(--secondary-container)",
        "tertiary": "var(--tertiary)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "outline": "rgb(var(--outline) / <alpha-value>)",
        "surface-bright": "var(--surface-bright)",
        "on-primary-container": "var(--on-primary-container)",
        "secondary-dim": "var(--secondary-dim)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "surface-container-high": "var(--surface-container-high)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "on-secondary": "var(--on-secondary)",
        "surface-variant": "var(--surface-variant)",
        "surface-tint": "var(--surface-tint)",
        "error-container": "var(--error-container)",
        "surface-dim": "var(--surface-dim)",
        "background": "var(--background)",
        "outline-variant": "var(--outline-variant)",
        "surface-container-highest": "rgb(var(--surface-container-highest) / <alpha-value>)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "primary": "var(--primary)",
        "on-surface-variant": "var(--on-surface-variant)",
        "inverse-primary": "var(--inverse-primary)",
        "on-background": "var(--on-background)",
        "primary-dim": "var(--primary-dim)",
        "secondary-fixed": "var(--secondary-fixed)",
        "tertiary-dim": "var(--tertiary-dim)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "on-error-container": "var(--on-error-container)",
        "on-primary": "var(--on-primary)",
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px",
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [
    require("daisyui"),
    require("@tailwindcss/forms"),
  ],
  daisyui: {
    themes: [
      {
        brutalist: {
          "primary": "#000000",
          "primary-content": "#f8f8f8",
          "secondary": "#5e5f5f",
          "secondary-content": "#faf9f8",
          "accent": "#af3200",
          "accent-content": "#fff7f5",
          "neutral": "#2f3334",
          "neutral-content": "#faf9f9",
          "base-100": "#faf9f9",
          "base-200": "#f3f3f3",
          "base-300": "#e0e3e4",
          "base-content": "#2f3334",
          "info": "#5b6061",
          "success": "#4CAF7A",
          "warning": "#fc4c00",
          "error": "#af3200",
          
          "--primary-fixed": "#e2e2e2",
          "--surface-container": "#edeeee",
          "--on-tertiary-fixed": "#000000",
          "--primary-fixed-dim": "#d4d4d4",
          "--tertiary-container": "#fc4c00",
          "--on-tertiary-container": "#0e0100",
          "--on-surface": "47 51 52",
          "--on-secondary-container": "#515252",
          "--inverse-surface": "#0d0e0f",
          "--primary-container": "#e2e2e2",
          "--error": "#9e3f4e",
          "--on-primary-fixed-variant": "#5b5b5b",
          "--on-secondary-fixed-variant": "#5b5b5c",
          "--on-tertiary-fixed-variant": "#2e0700",
          "--on-secondary-fixed": "#3e3f40",
          "--surface": "250 249 249",
          "--error-dim": "#4f0116",
          "--on-tertiary": "#fff7f5",
          "--secondary": "#5e5f5f",
          "--on-error": "#fff7f7",
          "--surface-container-low": "#f3f3f3",
          "--secondary-container": "#e3e2e2",
          "--tertiary": "#af3200",
          "--on-primary-fixed": "#3f3f3f",
          "--inverse-on-surface": "#9d9d9d",
          "--outline": "119 123 124",
          "--surface-bright": "#faf9f9",
          "--on-primary-container": "#525252",
          "--secondary-dim": "#525353",
          "--tertiary-fixed": "#fc4c00",
          "--surface-container-high": "#e6e8e9",
          "--tertiary-fixed-dim": "#e64500",
          "--on-secondary": "#faf9f8",
          "--surface-variant": "#e0e3e4",
          "--surface-tint": "#5e5e5e",
          "--error-container": "#ff8b9a",
          "--surface-dim": "#d6dbdc",
          "--background": "#faf9f9",
          "--outline-variant": "#afb3b3",
          "--surface-container-highest": "#e0e3e4",
          "--secondary-fixed-dim": "#d5d4d4",
          "--primary": "#5e5e5e",
          "--on-surface-variant": "#5b6061",
          "--inverse-primary": "#ffffff",
          "--on-background": "#2f3334",
          "--primary-dim": "#525252",
          "--secondary-fixed": "#e3e2e2",
          "--tertiary-dim": "#9a2b00",
          "--surface-container-lowest": "#ffffff",
          "--on-error-container": "#782232",
          "--on-primary": "#f8f8f8",
        },
        "brutalist-dark": {
          "primary": "#ffffff",
          "primary-content": "#0a0a0a",
          "secondary": "#a1a1a1",
          "secondary-content": "#0a0a0a",
          "accent": "#fc4c00",
          "accent-content": "#ffffff",
          "neutral": "#1e1e1e",
          "neutral-content": "#e0e0e0",
          "base-100": "#0a0a0a",
          "base-200": "#121212",
          "base-300": "#1e1e1e",
          "base-content": "#e0e0e0",
          "info": "#777b7c",
          "success": "#4CAF7A",
          "warning": "#fc4c00",
          "error": "#ff4d4d",

          "--primary-fixed": "#242424",
          "--surface-container": "#1e1e1e",
          "--on-tertiary-fixed": "#ffffff",
          "--primary-fixed-dim": "#1a1a1a",
          "--tertiary-container": "#fc4c00",
          "--on-tertiary-container": "#ffffff",
          "--on-surface": "#e0e0e0",
          "--on-secondary-container": "#a1a1a1",
          "--inverse-surface": "#faf9f9",
          "--primary-container": "#242424",
          "--error": "#ff4d4d",
          "--on-primary-fixed-variant": "#a1a1a1",
          "--on-secondary-fixed-variant": "#a1a1a1",
          "--on-tertiary-fixed-variant": "#ff8b66",
          "--on-secondary-fixed": "#e0e0e0",
          "--surface": "#121212",
          "--error-dim": "#800000",
          "--on-tertiary": "#0a0a0a",
          "--secondary": "#a1a1a1",
          "--on-error": "#ffffff",
          "--surface-container-low": "#1a1a1a",
          "--secondary-container": "#2a2a2a",
          "--tertiary": "#fc4c00",
          "--on-primary-fixed": "#e0e0e0",
          "--inverse-on-surface": "#2f3334",
          "--outline": "#5b6061",
          "--surface-bright": "#1e1e1e",
          "--on-primary-container": "#e0e0e0",
          "--secondary-dim": "#a1a1a1",
          "--tertiary-fixed": "#fc4c00",
          "--surface-container-high": "#2a2a2a",
          "--tertiary-fixed-dim": "#af3200",
          "--on-secondary": "#121212",
          "--surface-variant": "#2a2a2a",
          "--surface-tint": "#a1a1a1",
          "--error-container": "#800000",
          "--surface-dim": "#0a0a0a",
          "--background": "#0a0a0a",
          "--outline-variant": "#3e3f40",
          "--surface-container-highest": "#333333",
          "--secondary-fixed-dim": "#1e1e1e",
          "--primary": "#e0e0e0",
          "--on-surface-variant": "#a1a1a1",
          "--inverse-primary": "#000000",
          "--on-background": "#e0e0e0",
          "--primary-dim": "#a1a1a1",
          "--secondary-fixed": "#2a2a2a",
          "--tertiary-dim": "#ff8b66",
          "--surface-container-lowest": "#050505",
          "--on-error-container": "#ff8b9a",
          "--on-primary": "#0a0a0a",
        },
      },
    ],
    darkTheme: "brutalist-dark",
    base: true,
    styled: true,
    utils: true,
  },
}
